- ignore: { name: "Avoid lambda" }
- ignore: { name: "Avoid lambda using `infix`" }
- ignore: { name: "Use (,)" }
- ignore: { name: "Use const" }
- ignore: { name: "Use tuple-section" }
- ignore: { name: "Use when" }
