- ignore: { name: "Avoid lambda" }
- ignore: { name: "Avoid lambda using `infix`" }
- ignore: { name: "Eta reduce" }
- ignore: { name: "Replace case with maybe" }
- ignore: { name: "Use (,)" }
- ignore: { name: "Use const" }
- ignore: { name: "Use lambda-case" }
- ignore: { name: "Use tuple-section" }
- ignore: { name: "Use when" }
